version: '3.4'
services:
  NIRE_SCADA:
    #network_mode: "host"
    container_name: NIRE_SCADA
    hostname: NIRE_SCADA
    build:
      context: .
      dockerfile: Dockerfile-dev_NIRE_SCADA
      args:
        install_rmq: 'false'
    image: eclipsevolttron/volttron:v-docker-dev-latest
    ports:
      # host_port:container_port
      # http port for volttron central
      - 8443:8443
      - 22917:22917
    volumes:
      - ./platform_config_NIRE_SCADA.yml:/platform_config.yml
      - ./configs:/home/volttron/configs
      - ./core:/startup
      - NIRE_SCADA-data:/home/volttron/db
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000

volumes:
  NIRE_SCADA-data:
    name: NIRE_SCADA-data
