# Properties to be added to the root config file
# the properties should be ingestible for volttron
# the values will be presented in the config file
# as key=value
config:
  vip-address: tcp://0.0.0.0:22918
  # For rabbitmq this should match the hostname specified in
  # in the docker compose file hostname field for the service.
  #bind-web-address: https://192.168.10.254:8445
  #volttron-central-address: https://192.168.10.254:8445
  instance-name: Building_540
  message-bus: zmq # allowed values: zmq, rmq
  # volttron-central-serverkey: a different key

# Agents dictionary to install. The key must be a valid
# identity for the agent to be installed correctly.
agents:

  # Each agent identity.config file should be in the configs
  # directory and will be used to install the agent.
   listener:
     source: $VOLTTRON_ROOT/examples/ListenerAgent
     config: $CONFIG/listener.config
     tag: listener
   EMSDataForwarder:
     source: $VOLTTRON_ROOT/OPAL/EMSDataForwader
     config: $VOLTTRON_ROOT/OPAL/EMSDataForwader/config
     tag: EMSDataForwarderagent
   HMIControl:
     source: $VOLTTRON_ROOT/OPAL/HMIcontrol
     config: $VOLTTRON_ROOT/OPAL/HMIcontrol/config
     tag: HMIControlagent
   GAMSControl:
     source: $VOLTTRON_ROOT/OPAL/GAMScontrolAgent
     config: $VOLTTRON_ROOT/OPAL/GAMScontrolAgent/config
     tag: GAMSControlagent


   platform.driver:
     source: $VOLTTRON_ROOT/services/core/PlatformDriverAgent

     config_store:
    #Battery
        registry_configs/Battery.csv:
          file: $VOLTTRON_ROOT/Config_RTAC/Battery.csv
          type: --csv
        devices/building540/storage/Battery:
          file: $VOLTTRON_ROOT/Config_RTAC/Battery.config
    #  #SMART METERS
    #     registry_configs/SM1.csv:
    #       file: $VOLTTRON_ROOT/Config_RTAC/SM2.csv
    #       type: --csv
    #     devices/building540/meters/SM1:
    #       file: $VOLTTRON_ROOT/Config_RTAC/SM1.config
    #     registry_configs/SM2.csv:
    #       file: $VOLTTRON_ROOT/Config_RTAC/SM2.csv
    #       type: --csv
    #     devices/building540/meters/SM2:
    #       file: $VOLTTRON_ROOT/Config_RTAC/SM2.config
    #     registry_configs/SM3.csv:
    #       file: $VOLTTRON_ROOT/Config_RTAC/SM2.csv
    #       type: --csv
    #     devices/building540/meters/SM3:
    #       file: $VOLTTRON_ROOT/Config_RTAC/SM3.config
    #     registry_configs/SM4.csv:
    #       file: $VOLTTRON_ROOT/Config_RTAC/SM2.csv
    #       type: --csv
    #     devices/building540/meters/SM4:
    #       file: $VOLTTRON_ROOT/Config_RTAC/SM4.config
    # BERGY
        registry_configs/Bergey.csv:
          file: $VOLTTRON_ROOT/Config_RTAC/registry_configs_bergey_reg.csv
          type: --csv
        devices/building540/meters/Bergey:
          file: $VOLTTRON_ROOT/Config_RTAC/Bergey.config
    # # Ecobee
    #     registry_configs/Ecobee.csv:
    #       file: $VOLTTRON_ROOT/Config_RTAC/Ecobee.csv
    #       type: --csv
    #     devices/building540/thermostat/Ecobee:
    #       file: $VOLTTRON_ROOT/Config_RTAC/ecobee.config
    # JuiceBoxEV
    #     registry_configs/JuiceBoxEv.csv:
    #       file: $VOLTTRON_ROOT/Config_RTAC/JuiceBoxEv.csv
    #       type: --csv
    #     devices/building540/thermostat/JuiceBoxEv:
    #       file: $VOLTTRON_ROOT/Config_RTAC/JuiceBoxEv.config   
    # # GAMS
    #     registry_configs/GAMS.csv:
    #       file: $VOLTTRON_ROOT/Config_RTAC/GAMS.csv
    #       type: --csv
    #     devices/building540/GAMS:  
    #  tag: Masterdriver
  # platform.agent:
  #   source: $VOLTTRON_ROOT/services/core/VolttronCentralPlatform
  #   config: $CONFIG/vcp.config
  #   tag: vcp

  # platform.actuator:
  #   source: $VOLTTRON_ROOT/services/core/ActuatorAgent
  #   tag: actuator

  # platform.historian:
  #   source: $VOLTTRON_ROOT/services/core/SQLHistorian
  #   config: $CONFIG/historian.config
  #   tag: historian

  # volttron.central:
  #   source: $VOLTTRON_ROOT/services/core/VolttronCentral
  #   config: $CONFIG/vc.config
  #   tag: vc


#  weather:
#    source: $VOLTTRON_ROOT/examples/DataPublisher
#    config: $CONFIG/weather.config

#  price:
#    source: $VOLTTRON_ROOT/examples/DataPublisher
#    config: $CONFIG/price.config

#  platform.bacnet_proxy:
#    source: $VOLTTRON_ROOT/services/core/BACnetProxy
#    config: $CONFIG/bacnet-proxy.json
