# Properties to be added to the root config file
# the properties should be ingestible for volttron
# the values will be presented in the config file
# as key=value
config:
  vip-address: tcp://0.0.0.0:22919
  # For rabbitmq this should match the hostname specified in
  # in the docker compose file hostname field for the service.
  #bind-web-address: https://192.168.10.254:8445
  #volttron-central-address: https://192.168.10.254:8445
  instance-name: GLEAMM
  message-bus: zmq # allowed values: zmq, rmq
  # volttron-central-serverkey: a different key

# Agents dictionary to install. The key must be a valid
# identity for the agent to be installed correctly.
agents:

  # Each agent identity.config file should be in the configs
  # directory and will be used to install the agent.
   listener:
     source: $VOLTTRON_ROOT/examples/ListenerAgent
     config: $CONFIG/listener.config
     tag: listener
   EMSDataForwarder:
     source: $VOLTTRON_ROOT/OPAL/EMSDataForwader
     config: $VOLTTRON_ROOT/OPAL/EMSDataForwader/config
     tag: EMSDataForwarderagent
   HMIControl:
     source: $VOLTTRON_ROOT/OPAL/HMIcontrol
     config: $VOLTTRON_ROOT/OPAL/HMIcontrol/config
     tag: HMIControlagent
   platform.driver:
     source: $VOLTTRON_ROOT/services/core/PlatformDriverAgent

     config_store:
        registry_configs/RTACHREXTRA.csv:
          file: $VOLTTRON_ROOT/Config_RTAC/RTACHREXTRA.csv
          type: --csv
        devices/building540/storage/RTACHREXTRA:
          file: $VOLTTRON_ROOT/Config_RTAC/RTACHREXTRA.config

        registry_configs/Total.csv:
          file: $VOLTTRON_ROOT/Config_RTAC/Total.csv
          type: --csv
        devices/building540/storage/Total:
          file: $VOLTTRON_ROOT/Config_RTAC/Total.config

        registry_configs/RTAC.csv:
          file: $VOLTTRON_ROOT/Config_RTAC/RTAC.csv
          type: --csv
        devices/building540/storage/RTAC:
          file: $VOLTTRON_ROOT/Config_RTAC/RTAC.config

        registry_configs/RTACHRC.csv:
          file: $VOLTTRON_ROOT/Config_RTAC/RTACHRC.csv
          type: --csv
        devices/building540/storage/RTACHRC:
          file: $VOLTTRON_ROOT/Config_RTAC/RTACHRC.config    

        registry_configs/RTACHRI.csv:
          file: $VOLTTRON_ROOT/Config_RTAC/RTACHRI.csv
          type: --csv
        devices/building540/storage/RTACHRI:
          file: $VOLTTRON_ROOT/Config_RTAC/RTACHRI.config     

        registry_configs/RTACHRL4.csv:
          file: $VOLTTRON_ROOT/Config_RTAC/RTACHRL4.csv
          type: --csv
        devices/building540/storage/RTACHRL4:
          file: $VOLTTRON_ROOT/Config_RTAC/RTACHRL4.config    

        registry_configs/RTACHRL5.csv:
          file: $VOLTTRON_ROOT/Config_RTAC/RTACHRL5.csv
          type: --csv
        devices/building540/storage/RTACHRL5:
          file: $VOLTTRON_ROOT/Config_RTAC/RTACHRL5.config    


        registry_configs/RTACHRP.csv:
          file: $VOLTTRON_ROOT/Config_RTAC/RTACHRP.csv
          type: --csv
        devices/building540/storage/RTACHRP:
          file: $VOLTTRON_ROOT/Config_RTAC/RTACHRP.config    

        registry_configs/RTACHRTotal.csv:
          file: $VOLTTRON_ROOT/Config_RTAC/RTACHRTotal.csv
          type: --csv
        devices/building540/storage/RTACHRTotal:
          file: $VOLTTRON_ROOT/Config_RTAC/RTACHRTotal.config    

  # platform.agent:
  #   source: $VOLTTRON_ROOT/services/core/VolttronCentralPlatform
  #   config: $CONFIG/vcp.config
  #   tag: vcp

  # platform.actuator:
  #   source: $VOLTTRON_ROOT/services/core/ActuatorAgent
  #   tag: actuator

  # platform.historian:
  #   source: $VOLTTRON_ROOT/services/core/SQLHistorian
  #   config: $CONFIG/historian.config
  #   tag: historian

  # volttron.central:
  #   source: $VOLTTRON_ROOT/services/core/VolttronCentral
  #   config: $CONFIG/vc.config
  #   tag: vc


#  weather:
#    source: $VOLTTRON_ROOT/examples/DataPublisher
#    config: $CONFIG/weather.config

#  price:
#    source: $VOLTTRON_ROOT/examples/DataPublisher
#    config: $CONFIG/price.config

#  platform.bacnet_proxy:
#    source: $VOLTTRON_ROOT/services/core/BACnetProxy
#    config: $CONFIG/bacnet-proxy.json
