# For details on the structure of rabbitmq.config, see https://volttron.readthedocs.io/en/develop/platform-features/message-bus/rabbitmq/rabbitmq-volttron.html#configuration

# Although host parameter is required, it is not required for demo purposes because the parameter will be
# overwritten by core/setup-platform.py with the hostname specified in docker-compose
# host: vc

# mandatory. certificate data used to create root ca certificate. Each volttron
# instance must have unique common-name for root ca certificate
certificate-data:
  country: US
  state: Washington
  location: Richland
  organization: PNNL
  organization-unit: VOLTTRON Team
  common-name: volttron1-root-ca # should match the common-name defined during the CA creation routine in core/setup-platform.py

#
# optional parameters for single instance setup
#
# virtual-host: 'volttron' # defaults to volttron

# use the below four port variables if using custom rabbitmq ports
# defaults to 5672
# amqp-port: '5672'

# defaults to 5671
# amqp-port-ssl: '5671'

# defaults to 15672
# mgmt-port: '15672'

# defaults to 15671
# mgmt-port-ssl: '15671'

# defaults to true
# ssl: 'true'

# defaults to ~/rabbitmq_server/rabbbitmq_server-3.7.7
# overwritten by core/setup-platform.py with the RMQ_HOME env var defined in Dockerfile
# rmq-home: "~/rabbitmq_server/rabbitmq_server-3.7.7"
